// AI Prompt Processing Edge Function
// Verifies credits, calls AI API, deducts credits on success

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY");

const PRICE_PER_PROMPT = 0.10; // MNEE

Deno.serve(async (req) => {
  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
  };

  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const { walletAddress, prompt, sessionId } = await req.json();

    if (!walletAddress || !prompt) {
      throw new Error("Missing wallet address or prompt");
    }

    const address = walletAddress.toLowerCase();

    // Verify session if provided
    if (sessionId) {
      const sessionResp = await fetch(
        `${SUPABASE_URL}/rest/v1/sessions?id=eq.${sessionId}&wallet_address=eq.${address}&select=*`,
        {
          headers: {
            "Authorization": `Bearer ${SERVICE_ROLE_KEY}`,
            "apikey": SERVICE_ROLE_KEY,
          }
        }
      );
      const sessions = await sessionResp.json();
      if (!sessions || sessions.length === 0) {
        throw new Error("Invalid session");
      }
      const session = sessions[0];
      if (new Date(session.expires_at) < new Date()) {
        throw new Error("Session expired");
      }
    }

    // Check balance
    const profileResp = await fetch(
      `${SUPABASE_URL}/rest/v1/profiles?wallet_address=eq.${address}&select=total_credits_mnee`,
      {
        headers: {
          "Authorization": `Bearer ${SERVICE_ROLE_KEY}`,
          "apikey": SERVICE_ROLE_KEY,
        }
      }
    );
    const profiles = await profileResp.json();

    if (!profiles || profiles.length === 0) {
      throw new Error("Profile not found");
    }

    const balance = parseFloat(profiles[0].total_credits_mnee);
    if (balance < PRICE_PER_PROMPT) {
      throw new Error(`Insufficient balance. Need ${PRICE_PER_PROMPT} MNEE, have ${balance}`);
    }

    // Call AI API
    let aiResponse: string;

    if (GROQ_API_KEY) {
      // Real Groq API call
      const groqResp = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${GROQ_API_KEY}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: "llama3-8b-8192",
          messages: [
            { role: "system", content: "You are a helpful assistant." },
            { role: "user", content: prompt }
          ],
          max_tokens: 500
        })
      });

      if (!groqResp.ok) {
        const errText = await groqResp.text();
        throw new Error(`AI API error: ${errText}`);
      }

      const groqData = await groqResp.json();
      aiResponse = groqData.choices?.[0]?.message?.content || "No response generated";
    } else {
      // Fallback: Use a free API or simple response
      // Using a simple echo with enhancement for demo
      aiResponse = `[AI Response to: "${prompt.substring(0, 50)}..."]\n\nThank you for your prompt. This response was generated by the Pay-Per-Prompt system.\n\nTo enable full AI capabilities, configure GROQ_API_KEY in your Supabase Edge Function secrets.\n\nYour prompt has been processed and ${PRICE_PER_PROMPT} MNEE has been deducted from your balance.`;
    }

    // Deduct credits using RPC
    const deductResp = await fetch(`${SUPABASE_URL}/rest/v1/rpc/deduct_credits`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${SERVICE_ROLE_KEY}`,
        "apikey": SERVICE_ROLE_KEY,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        p_wallet_address: address,
        p_amount: PRICE_PER_PROMPT
      })
    });

    const deductResult = await deductResp.json();

    if (!deductResult.success) {
      throw new Error(deductResult.error || "Failed to deduct credits");
    }

    return new Response(JSON.stringify({
      success: true,
      response: aiResponse,
      newBalance: deductResult.new_balance,
      cost: PRICE_PER_PROMPT
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" }
    });

  } catch (error) {
    return new Response(JSON.stringify({
      success: false,
      error: error.message
    }), {
      status: 400,
      headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
});
